### ISSUE TITLE
Build Error: rcssmin

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#38]
Getting build error

```
Collecting rcssmin==1.0.6 (from django-compressor==2.0->mayan-edms==v2.1.4)
  Downloading rcssmin-1.0.6.tar.gz (582kB)
    100% |################################| 583kB 2.2MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/rcssmin.egg-info
    writing pip-egg-info/rcssmin.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/rcssmin.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/rcssmin.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/rcssmin.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_Qbo_k/rcssmin/setup.py", line 42, in <module>
        setup()
      File "/tmp/pip-build-_Qbo_k/rcssmin/setup.py", line 33, in setup
        return run(script_args=args, ext=ext, manifest_only=_manifest)
      File "_setup/py2/setup.py", line 421, in run
        return _core.setup(**kwargs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/share/mayan-edms/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 279, in run
        self.find_sources()
      File "/usr/share/mayan-edms/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
        mm.run()
      File "/usr/share/mayan-edms/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 533, in run
        self.add_defaults()
      File "/usr/share/mayan-edms/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "/usr/share/mayan-edms/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 35, in add_defaults
        self._add_defaults_data_files()
      File "/usr/share/mayan-edms/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 111, in _add_defaults_data_files
        dirname, filenames = item
    TypeError: 'Documentation' object is not iterable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_Qbo_k/rcssmin/
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 1

```

**Comment by DocCyblade** [comment]
It seems that the only thing that changed was [setuptools](https://pypi.python.org/pypi/setuptools) it was updated yesterday.

**Comment by DocCyblade** [comment]
[Found this issue](https://github.com/pypa/setuptools/issues/833), it seems to be library used for PIP/setup and causes the issue.

**Comment by DocCyblade** [comment]
Workaround would be to
`pip install -U pip wheel setuptools==28.6.1`

**Comment by DocCyblade** [comment]
Keeping this open until the setuptools is patched and we can remove the workaround

**Comment by DocCyblade** [comment]
This has been fixed upstream and can be closed
